# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: main_user
  password: samara

development:
  <<: *default
  database: nowa_alfa_development
  username: main_user
  password: samara

test:
  <<: *default
  database: nowa_alfa_test
  username: main_user
  password: samara